# General

site_name: Data Package Library
site_url: https://frictionlessdata.github.io/dplib-py
site_author: Open Knowledge Foundation
site_description: Python implementation of the Data Package standard
repo_name: frictionlessdata/dplib-py
repo_url: https://github.com/frictionlessdata/dplib-py
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 <a href="https://okfn.org">Open Knowledge Foundation</a>

# Theme

theme:
  name: material
  custom_dir: docs/.theme
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-dark.svg
  favicon: assets/favicon.ico

# Plugins

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            show_root_heading: true
            show_if_no_docstring: true
            heading_level: 3

# Extras

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frictionlessdata
      name: Code on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/okfn
      name: Follow us on Twitter

# Extensions

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
      # toc_depth: 4
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true

# Navigation

nav:
  - Home:
      - Welcome: index.md
      - Installation: installation.md
      - Working with Models: working-with-models.md
      - Validating Metadata: validating-metadata.md
      - Converting Metadata: converting-metadata.md
      - Contributing: contributing.md
      - Changelog: changelog.md
  - Models:
      - Package: models/package.md
      - Resource: models/resource.md
      - Dialect: models/dialect.md
      - Schema: models/schema.md
  - Actions:
      - Package: actions/package.md
      - Resource: actions/resource.md
      - Dialect: actions/dialect.md
      - Schema: actions/schema.md
  - Plugins:
      - CKAN: plugins/ckan.md
      - CLI: plugins/cli.md
      - DataCite: plugins/datacite.md
      - DCAT: plugins/dcat.md
      - GitHub: plugins/github.md
      - Pandas: plugins/pandas.md
      - Polars: plugins/polars.md
      - SQL: plugins/sql.md
      - Zenodo: plugins/zenodo.md
