# General

site_name: dplib-py
site_url: https://frictionlessdata.github.io/dplib-py
site_author: Open Knowledge Foundation
site_description: Python implementation of the Data Package standard
repo_name: frictionlessdata/dplib-py
repo_url: https://github.com/frictionlessdata/dplib-py
copyright: Copyright &copy; 2023 <a href="https://okfn.org">Open Knowledge Foundation</a>

# Theme

theme:
  name: material
  custom_dir: docs/.theme
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/favicon.png
  favicon: assets/favicon.png

# Plugins

plugins:
  - mkdocstrings

# Extras

extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/frictionlessdata
      name: Code on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/okfn
      name: Follow us on Twitter

# Extensions

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true

# Navigation

nav:
  - Documentation:
      Installation: documentation/installation.md
      Usage: documentation/usage.md
  - Reference:
      Schema: reference/schema.md
  - Contributing:
      Development: contributing/development.md
